# Generated by Django 3.2.6 on 2021-08-07 08:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_company_email_interaction_name_phone_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='date_edit',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 8, 7, 8, 48, 27, 734358, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_edit',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_edit',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.company'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.company'),
        ),
    ]
