# Generated by Django 3.2.6 on 2021-08-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210807_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='company',
        ),
    ]
