# Generated by Django 3.2.6 on 2021-08-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_interaction_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='adress',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='descr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_comp',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='email',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='channel_of_reference',
            field=models.CharField(choices=[('З', 'Заявка'), ('П', 'Письмо'), ('С', 'Сайт'), ('И', 'Инициатива компании')], max_length=20, verbose_name='Канал обращения'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='descr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='name',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.CharField(max_length=100, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончания работ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(verbose_name='Дата начала работ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='descr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
