# Generated by Django 3.2.6 on 2021-08-09 14:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210809_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='descr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
