# Generated by Django 3.2.6 on 2021-08-11 12:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_company_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='descr',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='manager',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='project',
            name='descr',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
